console.log("script running")
document.querySelector('.cross').style.display='none';
document.querySelector('.menu').addEventListener("click",()=>{
    document.querySelector('.sidebar').classList.toggle('sidebargo');
if(document.querySelector('.sidebar').classList.contains('sidebargo')){
    document.querySelector('.menu').style.display='inline'
    document.querySelector('.cross').style.display='none'
}
else{
    document.querySelector('.menu').style.display='none';
    setTimeout(()=>{
    document.querySelector('.cross').style.display='inline';
},400);
}
})
document.querySelector('.cross').addEventListener("click",()=>{
    document.querySelector('.menu').style.display='inline';
    document.querySelector('.sidebar').classList.toggle('sidebargo');
    document.querySelector('.cross').style.display='none';
})